IF (NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_NAME = 'T_User'))
BEGIN
    CREATE TABLE T_User (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Username VARCHAR(255) UNIQUE,
    Password VARCHAR(MAX)
);
END

IF (NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_NAME = 'T_Blog'))
BEGIN
    CREATE TABLE T_Blog (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Title VARCHAR(100),
    Content VARCHAR(MAX),
    Author_ID INT,
    FOREIGN KEY (Author_ID) REFERENCES T_User(ID)
);
END


IF (NOT EXISTS (SELECT *  FROM T_User WHERE  ID = 1))
BEGIN
    INSERT INTO T_User([Username],[Password]) VALUES ('admin','$2b$08$7kG3N0Kyocsmco8WT0HYF.AVJ6cDwQ6J7OntzTXynrdP8YXHlnBmC')
END